### ISSUE TITLE
Add qibla direction finder

### ISSUE THREAD

**Issue by amgadelsaiegh** [meypod/al-azan#1]
First, thank you for the effort
- it will be nice to make a mini app in the main app to help the user to find qibla direction.

**Comment by meypod** [comment]
The goal of this app was to be specifically for Adhan, so I'm not sure about adding anything outside It's goal, so It's currently not on the roadmap
I will probably create an open source qibla finder as a separate app later

**Comment by meypod** [comment]
added qibla finder in 1.11.0
