### ISSUE TITLE
Add calculation methode: Indonesia

### ISSUE THREAD

**Issue by muava12** [meypod/al-azan#10]
Hi, can you add calculation method for Indonesia

methode name: Kementrian Agama Republik Indonesia (KEMENAG)
Fajr: 20.0°
Isya: 18.0°

**Comment by meypod** [comment]
please translate the added key related to this

**Comment by meypod** [comment]
I realized its in indonesian, no need then

**Comment by muava12** [comment]
Done 👌

**Comment by meypod** [comment]
thanks
