### ISSUE TITLE
Notifee Library Issue

### ISSUE THREAD

**Issue by hypesol** [meypod/al-azan#100]
I am getting this issue on compilation.

==================

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':notifee_react-native:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':notifee_react-native:debugCompileClasspath'.
   > Could not resolve project :notifee_core.
     Required by:
         project :notifee_react-native
      > No matching configuration of project :notifee_core was found. The consumer was configured to find a component for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.2' but:
          - None of the consumable configurations have attributes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by meypod** [comment]
Hi
make sure you have followed "[how-to-run-this-project](https://github.com/meypod/al-azan#how-to-run-this-project)" steps properly

this is probably caused by not initializing the git submodule properly
check if you have the "notifee_fork" directory and it has files inside
if you didn't have the directory, run this command inside the root directory of the project:
```bash
git submodule update --init --recursive
```

**Comment by hypesol** [comment]
Hi
"notifee_fork" this directory is existing in project folder but that is empty
and I have already run above command but i am getting this error

![image](https://github.com/meypod/al-azan/assets/14737991/4bc3e71e-d40e-4df7-9c63-68c4ecdd8218)

**Comment by meypod** [comment]
Hi
You haven't clone the repository properly then
clone again using this command:
```
git clone --recurse-submodules git@github.com:meypod/al-azan.git
```
