### ISSUE TITLE
صلاحية تجاهل تحسين البطارية

### ISSUE THREAD

**Issue by islam2hamy** [meypod/al-azan#103]
السلام عليكم

**Is your feature request related to a problem? Please describe.**

عدم بدء المنبه فى وقته , بالرغم من تفعيل عدم تحسين البطارية وكذلك التشغيل التلقائى للبرنامج

**Describe the solution you'd like**

android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

اضافة هذه الصلاحية للتطبيق تحل المشكلة فى جميع الاجهز ان شاء الله

وذلك عن تجربة مع برامج اخرى بها هذه الصلاحية

**Comment by AI-IMED** [comment]
أخي.. الميزة موجودة بالفعل ، عليك بتبديل الحالة من "مفعل" الى "غير مفعل" .

![٢٠٢٣١٠٢٠_٠٨٤٩١٢](https://github.com/meypod/al-azan/assets/38974362/b5bfdb7b-bcda-4bbf-bb2d-bd6b1e0daa72)

**Comment by islam2hamy** [comment]
لا هذه صلاحة أقوى
انا بالفعل مفعل هذه الميزة

**Comment by meypod** [comment]
سبب عدم إضافة هذا الإذن هو أنه يبدو أن Google تزيل التطبيقات دون أي تحذيرات في حالة استخدامها:

https://stackoverflow.com/questions/39787886/how-we-can-make-sure-we-are-allowed-to-use-request-ignore-battery-optimizations
https://www.reddit.com/r/androiddev/comments/3s9ggu/psa_declaring_request_ignore_battery/

**Comment by islam2hamy** [comment]
لكنها تسمح به فى حالة كان البرناج يحتوى على منه او اشعارات مهمة

https://play.google.com/store/apps/details?id=com.haz.prayer

**Comment by islam2hamy** [comment]
الصلاحية فى هذا التطبيق مثلا , يتم تنفيذها بعد موافقة المستخدم يضغطه على زر داخل التطبيق

**Comment by meypod** [comment]
أنا متأكد من أنه من الممكن استخدامه، لكنه يأتي مع خطر إزالة التطبيق دون أي تحذير لأنه ليس من الواضح تحت أي ظروف يُسمح به

ليس من الممكن تغيير هذا الإعداد دون تأكيد المستخدم على أي حال، لذا فهذه ليست المشكلة

**Comment by islam2hamy** [comment]
لا مشكلة أخى , انت أعلم منى 
فقط أردت عرض الفكرة لعلها تكون مفيدة

**Comment by meypod** [comment]
شكرًا لك
أبقي هذه المشكلة مفتوحة وأحاول إضافة هذا الإذن عندما يحصل التطبيق على المزيد من التنزيلات على Google Play، ونأمل ألا تتم إزالته بعد ذلك

**Comment by islam2hamy** [comment]
ان شاء الله

بارك الله فيك وجازاك خيرا

**Comment by meypod** [comment]
وقد تم تنفيذ هذا في أحدث الإصدارات
شكرًا لك
