### ISSUE TITLE
الاطلاع على كم بقي للصلوات الأخرى

### ISSUE THREAD

**Issue by ayman17ah** [meypod/al-azan#108]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by meypod** [comment]
أين تقصد؟
إذا كنت تقصد في المصغر، فقد تم طرح ذلك بالفعل، وقد أوضحت سبب عدم إضافتها (بسبب استخدام البطارية)
