### ISSUE TITLE
Simplify Onboarding

### ISSUE THREAD

**Issue by joewood9364** [meypod/al-azan#111]
**Is your feature request related to a problem? Please describe.**
On first-use the app has too many steps and is cumbersome.

**Describe the solution you'd like**
 Users ideally shouldn't be asked to straight-away configure advanced settings such as latitude, longitude, advanced notifications, system battery optimisation etc.
You should aim to automatically set good defaults out of the box and reduce the number of setup pages.

**Comment by meypod** [comment]
well It may look confusing, but selecting a method and setting coordinates is the bare minimum that must be configured.

**Comment by meypod** [comment]
disabling battery optimizations is necessary for when user wants to use the app for playing adhan or send notifications reliably and usually the point of using the app is to do that
which makes up the steps of onboarding

and non of these can be done automatically without user interaction

so I don't think setting good defaults makes any sense.
