### ISSUE TITLE
Self Hosted Prayer Times

### ISSUE THREAD

**Issue by n4b7l** [meypod/al-azan#115]
First of all thank you a lot for developing such an app with privacy in mind. Instead of prayer time calculation, can you please add an option to fetch prayer time from a self hosted server? So we will get exact time of prayer. We will update prayer time in our self hosted server when required

**Comment by meypod** [comment]
Hi
at the moment the development is paused, as I am very busy with my work life
that aside, when I get back to this project, I want to separate the qibla map into another app, and remove the internet permission from the app for increased privacy, so the feature you have in mind cannot be implemented later on

you can fork the app and create a version that suits your needs, as long as you don't violate the license (make it open source, mention the source, mention the changes, etc.) and please don't add ads.
