### ISSUE TITLE
The newest APK refuses to install

### ISSUE THREAD

**Issue by najjara** [meypod/al-azan#116]
**Describe the bug**
 
Installing the newest version causes PackageInstaller to crash.
The happens no matter which architecture is used.
The same happens when trying to install the APK from GitHub.

At first the newer version refused to update. I cleared cache, backed-up the app then cleared data, but didn't help. I finally uninstalled the installed version, and tried to install a fresh one... but still the same issue that prevented updating, prevents installing.

The APKs download without errors and can be opened without issues (using a archive tool). Their sizes match the size published. Since there aren't any published checksums, I can't definitely verify the integrity of the archives, but I don't have reason to believe they're corrupt.

**To Reproduce**

Try to install a new version or update the existing app
Android PackageInstaller will hang, then display a message that says "Package Installer keeps stopping" with the options "App info" or "Close app".

**Expected behavior**

The app should install without issues.

**Screenshots**
![Screenshot_20240210-150355](https://github.com/meypod/al-azan/assets/12216960/af246254-247b-4bc9-af5a-a12f9239642e)
![Screenshot_20240210-150502](https://github.com/meypod/al-azan/assets/12216960/9dfe2bcf-5ac8-4654-9379-a1b547d8ec14)

**Device Info :**
 - Device: Google Pixel 6 Pro
 - OS: Android 14

**App Version:**
**F-Droid:** Yes

**Additional context**

Some online research mentioned that this could be caused by an usually large icon, but I see this isn't the case here.
I should also mention that this started happening since 1.17.4. I was hoping the newest release would have fixed whatever the issue is, but it hasn't.

**Comment by meypod** [comment]
Hi
Thanks for reporting this issue
I'm not sure why this is happening
I haven't changed the icon for sure
I have the latest versions installed on my phone from GitHub, and I have tried installing previous versions and updating and both did without any problem

It may be a much more subtle issue, may be an issue with one of dependencies, or a very specific issue with your phone model

I'll try to update dependencies soon and make a pre release to see if it resolves issue for you

**Comment by meypod** [comment]
Just to rule out other stuff and make sure this issue is actually related to the app, please try installing another apk, and try reinstalling again after a reboot and let me know of the results

Thank you

**Comment by najjara** [comment]
I have many apps installed through F-Droid, they all update without an issue.
Of all the apps, the only one with a similar error so far is SD Maid SE.
This is unrelated to reboots or cache.

The only thing that appears in `logcat` is:
`02-11 20:33:33.174  1755  1755 I NotificationService: Cannot find enqueued record for key: 0|org.fdroid.fdroid|1|https://f-droid.org/repo/com.github.meypod.al_azan_72003.apk|10272`

**Comment by meypod** [comment]
just a quick search, can you check if the solution in [this link](https://android.stackexchange.com/questions/255940/package-installer-keeps-stopping) is related ?

**Comment by najjara** [comment]
According to https://developer.android.com/reference/android/provider/Settings.Secure.html#SECURE_FRP_MODE this string has been deprecated in API level 34 (Android 14).

`adb` shows that `secure_frp_mode` and `global.secure_frp_mode` are both null

`adb shell settings get secure global.secure_frp_mode`

Setting them to `0` doesn't solve the issue.

**Comment by meypod** [comment]
Hi
please try the latest version:
https://github.com/meypod/al-azan/releases/tag/v1.17.6

I checked 1.17.4  and the only thing I changed was react native version
I have updated some of dependencies including react native
let me know how it goes

**Comment by najjara** [comment]
It still gives the same error

**Comment by meypod** [comment]
Is 1.17.3 installing without any problem for you right now ?

**Comment by najjara** [comment]
No.

**Comment by meypod** [comment]
So can you tell me which version is the last version you can install without any problem? 
You said it started happening on 1.17.4, but now you can't install 1.17.3, ao

**Comment by najjara** [comment]
I still can't figure out what the issue is. There are multiple apps in F-Droid that I can't install either (while other install without an issue). They all throw the same error.
Searching for the error returns very fresh results, which leads me to believe Google pushed something through Play perhaps (this started between OS updates, so it can't be that) that's causing this. Not many solutions yet.

**Comment by meypod** [comment]
I see
at least now we know it's not caused by some change in al-azan
I hope this issue gets fixed for you
please let me know if you find out any solution by posting here, as some other people may land on this issue through google search

**Comment by meypod** [comment]
I'm glad it's fixed
Thank you for letting me know

**Comment by najjara** [comment]
Yes, it's fixed. Thank you!
What was the issue?

**Comment by meypod** [comment]
I have updated react native version hoping that it would fix it but I don't think it was caused by any change in al-azan as older versions also started having the same issue
So I don't really have any idea what was the cause
