### ISSUE TITLE
Supporting development

### ISSUE THREAD

**Issue by koutheir** [meypod/al-azan#118]
I'd like to donate money in order to support the project developers. Can you make this an option in the app or on the website?

**Comment by meypod** [comment]
Hi
Sadly, as much as I'd like to get donations directly, due to reasons, the only way I can receive donation is through crypto.

**Comment by koutheir** [comment]
I don't have any crypto currency to donate, but if that's something you're willing to accept then maybe provide some documentation for people who own crypto currencies and would like to donate.

**Comment by meypod** [comment]
well, there is crypto wallet addresses in the readme
I'll try to add bitcoin and litecoin addresses to f-droid some time later to make it more obvious, but people looking for it can find it quite easily
