### ISSUE TITLE
التذكير فى يوم محدد

### ISSUE THREAD

**Issue by islam2hamy** [meypod/al-azan#119]
السلام عليكم

التذكير ليوم محدد لا يعمل معى

قم بعمل تذكير قبل صلاة الجمعه بـ ٢٥ دقيقة مثلا
انتظر يوم التذكير
التذكير لا يعمل لدى

![IMG_٢٠٢٤٠٢٢٣_١٦٣٦١٤](https://github.com/meypod/al-azan/assets/7989030/ef7b5921-1c4c-4b99-9f37-59fd6f10f0c3)

**Comment by meypod** [comment]
و علیکم السلام

شكرا للإبلاغ عن هذه المسألة
سأقوم بإصدار إصلاح لهذه المشكلة قريبًا جدًا

**Comment by meypod** [comment]
[v1.17.7](https://github.com/meypod/al-azan/releases/tag/v1.17.7)

**Comment by islam2hamy** [comment]
بارك الله فيك
ان شاء الله فى انتظاره على
f-droid
