### ISSUE TITLE
Faulty widget settings

### ISSUE THREAD

**Issue by 537** [meypod/al-azan#120]
**Describe the bug**
 Widget settings to hide notification prayer times is faulty, ticking something unticks something else

**To Reproduce**
Try to turn anything on and off. Somehow other timings turn on and off. Sometimes multiple timings turn on or off together

**Expected behavior**
Turning fajr on should turn fajr on and not turn anything else on or off

**Screenshots**
https://imgur.com/a/Cu76gS0

**Device Info**
 - Device: Pixel 6
 - OS: Android 14

**App Version:** 1.17.6
**F-Droid:** Yes

**Additional context**
No

**Comment by meypod** [comment]
Im sorry but can't understand the issue you are describing and the image does not load
Please upload the image directly to github

**Comment by meypod** [comment]
Thank you
This is definitely a bug and should not happen
I'll work on it soon

**Comment by meypod** [comment]
It seems It's not going to be that easy as it's a bug in the UI library I'm using:

https://github.com/GeekyAnts/NativeBase/issues/5073

I'm investigating the possible short term fixes, if I cannot find any, I have to change the UI completely probably

**Comment by meypod** [comment]
fixed the issue
will be released on [1.17.8](https://github.com/meypod/al-azan/releases/tag/v1.17.8)
