### ISSUE TITLE
Display city name alongside coordinates

### ISSUE THREAD

**Issue by yusufmte** [meypod/al-azan#121]
Suggestion; Display current city name alongside coordinates.

**Comment by meypod** [comment]
when the location is named, or coordinates is determined by the city name, the name is shown by default
can you maybe explain by a screenshot what is not working as you expect ?
if you mean that the app detect which city you are in by checking the coordinates, it is not possible currently.

**Comment by yusufmte** [comment]
Oh, I did mean that the app detect city by checking coordinates -- no
worries if not possible, feel free to close this! Thank you!!
