### ISSUE TITLE
Fajr Azan

### ISSUE THREAD

**Issue by Abdulbaari93** [meypod/al-azan#13]
Thank you for the beautiful app. 

This is exactly what I wanted. 

Can just this be added?  Fajr Azan is different than the other Prayers is there some way to change just the Fajr Azan and keep the rest the same?

**Comment by meypod** [comment]
thanks
you mean the time ? 
adhan times can be adjusted independently in calculation settings, this is just added recently. if you are on f-droid you would have to wait till f-droid releases the updated version
you can always download the updates faster from GitHub releases, It's exactly the same app, It just doesn't have auto update benefit of f-droid

**Comment by Abdulbaari93** [comment]
No, the Fajr Azan sound, Fajr Azan is different from the other four prayers.

**Comment by meypod** [comment]
Oh, I see
I have to think about how to implement it

**Comment by meypod** [comment]
I've added this feature in [v1.6.0](https://github.com/meypod/al-azan/releases/tag/v1.6.0)
I hope this is what you've been looking for ;)

**Comment by Abdulbaari93** [comment]
Thanks alot, looking forward to it 👍 

Much appreciated!
