### ISSUE TITLE
Add FOSS-version to Github Releases.

### ISSUE THREAD

**Issue by ghost** [meypod/al-azan#137]
**Is your feature request related to a problem? Please describe.**
Currently the only way to get the FOSS version of this app is from F-Droid which has some security issues. 

**Describe the solution you'd like**
I would like the FOSS version to be available as a downloadable APK directly from Github Releases.

**Additional context**

**Comment by meypod** [comment]
I'll try to put some time to update the Libremap dependency to make the app completely foss on all variants soon, hopefully this also eliminates the need to have different variants

**Comment by ghost** [comment]
Closing as all releases are FOSS now. Thanks!
