### ISSUE TITLE
Question about Logger in the App

### ISSUE THREAD

**Issue by ghost** [meypod/al-azan#142]
Asselamu aleykum,

i saw that the App got one Log/Logger and I wanted to ask if it could be removed? I did found it with the Warden App from Gitlab/F-Droid. 

I added a Screenshot and I hope it can be removed. Thanks!

![IMG_20240902_104459](https://github.com/user-attachments/assets/93cfbd3c-f858-490c-9b68-866f3f17e0ce)

**Comment by meypod** [comment]
Wa alaykum assalam

It seems it's a logger used by [maplibre-react-native](https://github.com/maplibre/maplibre-react-native/) that I use to show Qibla map

it does not seem to be uploading anything anywhere though, so there shouldn't be any problem

If I want to remove it, I have to remove the Qibla map, so sadly no, I don't think it's removable

**Comment by IbrahimAkhii** [comment]
Oh interesting, I understand. Thank you for the Information. Okay, no Problem. I also use the Qibla App, so it would be sad.

**Comment by meypod** [comment]
the website is a very simple webpage built using different means, so it's not possible to do this right now. I'm sure it can be done though (as a different project), it's just a lot of work for me and right now I can't do it.
Thank you
