### ISSUE TITLE
solution for logger

### ISSUE THREAD

**Issue by ghost** [meypod/al-azan#144]
hey i noticed that the app has logger, can you change that or is there a solution? i have no Tracker or logger and it bothers me a bit to have one left. maybe you can find a solution for that? take your time for that.

**Comment by meypod** [comment]
Hi
The app does not use any logging sdk, it's probably the internal react native logger (no data is collected and no data is transmitted)
I cannot do anything about this at the moment, but a rewrite of the app is in the works, which will probably help with this issue.

**Comment by ghost** [comment]
Oh nice, will it be away after the rewrite or do you mean that it would be easier to change then?
