### ISSUE TITLE
App icon not showing on android N

### ISSUE THREAD

**Issue by deb-kolektor** [meypod/al-azan#17]
Only show default android icon on the drawer
![Screenshot_20221128-220636](https://user-images.githubusercontent.com/916555/204311429-5761f8a5-c52d-4204-b416-9d10309ffce9.png)

**Comment by meypod** [comment]
I'll check this on emulator soon

**Comment by meypod** [comment]
thanks for reporting this
I fixed it in https://github.com/meypod/al-azan/commit/25c4c4a6e6fa9b8c7c76f5bfd90a269507c42dd4
will be available in next release
