### ISSUE TITLE
[Feature] Material You adaptive icon

### ISSUE THREAD

**Issue by Anas-Sherif** [meypod/al-azan#24]

**Comment by meypod** [comment]
given that [adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) were added on android 13, this will be only supported on android 13+

I have added this feature, will be released in next version (~ v1.11.0)

this is how it might look:
<details>
  <summary>Expand to See Images</summary>

 ![image](https://user-images.githubusercontent.com/106489260/220357063-b45c1eac-6221-425b-95fb-aeb635714cf8.png)
 ![image](https://user-images.githubusercontent.com/106489260/220357141-cdab04c4-0d1c-4950-9ce4-2ff4433b9201.png)

</details>
