### ISSUE TITLE
Add an option to disable upcoming adhan notification

### ISSUE THREAD

**Issue by smehdux** [meypod/al-azan#26]
Salam Alykoum

In the sounds and notifications settings the application doesn't allow the enabling of sound without notification, if we check sound notification is checked too.

Is there any option to disable Azan notifications?

Thanks in advance 

Version 1.9.0

**Comment by meypod** [comment]
wa alaykum assalam

it may not be obvious, but if it doesn't show any notification how can you stop the sound without opening the app ?
and android does not allow such behavior in general, It's an OS limitation :)

**Comment by smehdux** [comment]
> wa alaykum assalam
> 
> it may not be obvious, but if it doesn't show any notification how can you stop the sound without opening the app ? and android does not allow such behavior in general (you cannot play a sound without showing a notification), It's an OS limitation :)

Sorry I mean the notification a while  before Azan.
How can I disable it?

**Comment by meypod** [comment]
you mean the notification that has a button to cancel upcoming adhan ?

**Comment by smehdux** [comment]
> you mean the notification that has a button to cancel upcoming adhan ?

Yes 👍🏽

**Comment by meypod** [comment]
sadly there is no way to do that right now, I re-open this issue and add this as an option in future versions

**Comment by meypod** [comment]
added in 1.10.0
