### ISSUE TITLE
[SUGGESTION/BUG] Make the app not repeat prayers after phone was sleeping during the prayer time

### ISSUE THREAD

**Issue by Damaj301damaj-lol** [meypod/al-azan#28]
Thank you for your application it really helps me to go pray in the correct times!

However, as a student i am forced to turn off my device entirely during class time, which is during 7:30AM-3:10PM, by this time 2 prayers have passed, when i turn my phone on and unlock it and startup apps start, i get the first salah, then the second one directly after dismissing the first one, since the time has already passed and i can't pray that prayer anymore without "kada", so i wonder if i can make it stop doing that or perhaps if its a bug get it fixed.

Thank you

**Comment by meypod** [comment]
hi
I'm glad it's helping

thanks for reporting this
I think I exactly know why it does that, and I have a simple change in mind that can help prevent this issue, but it must be tested
despite it being easy to do, I'm in the middle of working on releasing qibla finder feature, which may take a week or two at max
after that I can apply the fix and release it with the qibla finder together
I'll let you know here when it's done, so you can test it and report back if that's working for you

**Comment by Damaj301damaj-lol** [comment]
> hi
> I'm glad it's helping
> 
> thanks for reporting this
> I think I exactly know why it does that, and I have a simple change in mind that can help prevent this issue, but it must be tested
> despite it being easy to do, I'm in the middle of working on releasing qibla finder feature, which may take a week or two at max
> after that I can apply the fix and release it with the qibla finder together
> I'll let you know here when it's done, so you can test it and report back if that's working for you

Oh ok i see, thanks!

**Comment by meypod** [comment]
Hi again
please try [1.11.1-rc](https://github.com/meypod/al-azan/releases/tag/v1.11.1-rc) and let me know if it fixes the issue for you
what to expect:
the alarm that has been set should still fire, but you shouldn't see all the prayers one by one
so only one alarm should show up and then app should continue working normally

**Comment by Damaj301damaj-lol** [comment]
Thanks!, will download it, and will try it

**Comment by Damaj301damaj-lol** [comment]
> Hi again
> please try [1.11.1-rc](https://github.com/meypod/al-azan/releases/tag/v1.11.1-rc) and let me know if it fixes the issue for you
> what to expect:
> the alarm that has been set should still fire, but you shouldn't see all the prayers one by one
> so only one alarm should show up and then app should continue working normally

It works!

**Comment by Damaj301damaj-lol** [comment]
> I'm glad it works, for now you have to continue using it, as my updates are blocked from f-droid for a while, so there wont be a stable release there that will contain this fix for now
> thanks for testing it 

Sad :(, i discovered your app on F-Droid

**Comment by meypod** [comment]
I know
[I'm working on getting it released on f-droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12697)
just it might take a while ( a week or two ) before I can release more updates there
