### ISSUE TITLE
Suggestion: stop adhan by pressing volume buttons

### ISSUE THREAD

**Issue by NeeeerD** [meypod/al-azan#29]
I wanna make a suggestion, when the app start the adhan, i would press the volume up or volume down to atop the adhan. Because somtimes im praying and my phone start the adhan and I don't want to pull my phone while im praying . جزاك الله خيرا

**Comment by meypod** [comment]
I have released this in [v1.12.0](https://github.com/meypod/al-azan/releases/tag/v1.12.0)

**Comment by meypod** [comment]
you can find it in the newly added `General` settings
