### ISSUE TITLE
am pm 

### ISSUE THREAD

**Issue by ahmed-tasaly** [meypod/al-azan#4]
Can you add 12 hours mode (am pm) ?

**Comment by meypod** [comment]
sure, I'll do it when I have time

**Comment by meypod** [comment]
I've added it in [v1.0.8](https://github.com/meypod/al-azan/releases/tag/v1.0.8), will be picked up by f-droid on the next cycle probably. it will be released on GitHub in the next hour as well.
reopen this if there's any issue in releasing to f-droid or if the feature is not working as intended
