### ISSUE TITLE
Ramadan

### ISSUE THREAD

**Issue by NeeeerD** [meypod/al-azan#40]
<details>
  <summary>Click to view images</summary>
  
![Screenshot_20230324_170141_Google](https://user-images.githubusercontent.com/127068987/227542070-1b689cc3-4df5-4316-818e-d63ce4ea7b27.jpg)
![Screenshot_20230324_170127_Al-Azan](https://user-images.githubusercontent.com/127068987/227542086-027647b3-de0f-4bf2-ab84-700837856e70.jpg)
  
</details>

 In ramadan the isha adhan time increases for about 30 minutes but in the app its still the same can you fix it

**Comment by meypod** [comment]
Hi 
Can you link to an article that explains that Isha time should be increased by about 30 minutes during Ramadan ?

**Comment by NeeeerD** [comment]
> Hi Can you link to an article that explains that Isha time should be increased by about 30 minutes during Ramadan ?

https://binbaz.org.sa/fatwas/15959/%D8%AD%D9%83%D9%85-%D8%AA%D8%A7%D8%AE%D9%8A%D8%B1-%D8%B5%D9%84%D8%A7%D8%A9-%D8%A7%D9%84%D8%B9%D8%B4%D8%A7%D8%A1-%D9%81%D9%8A-%D8%B1%D9%85%D8%B6%D8%A7%D9%86-%D9%88%D8%BA%D9%8A%D8%B1%D9%87

**Comment by NeeeerD** [comment]
> Hi Can you link to an article that explains that Isha time should be increased by about 30 minutes during Ramadan ?

Maybe this article i sent you but the time in Tabuk got increased by 30 min in Ramadan and thank you .

**Comment by meypod** [comment]
added adjustments in [v1.13.3](https://github.com/meypod/al-azan/releases/tag/v1.13.3)
you can reset your Isha time adjustments in calculation settings back to 0
from now on in `Umm al-Qura University` calculation method, it will automatically add 30 minutes in Ramadans and back to normal when Ramadan finishes.
