### ISSUE TITLE
Wrong lunar date 

### ISSUE THREAD

**Issue by NeeeerD** [meypod/al-azan#41]
It says Saturday Ramadan 4  but its Ramadan 3
<details>
  <summary>Click to view images</summary>

![Screenshot_20230325_113236_Al-Azan](https://user-images.githubusercontent.com/127068987/227706647-aea312c3-7ba0-437d-83dd-2c7718c075a6.jpg)

</details>

**Comment by meypod** [comment]
Hi
There's some inconsistencies between different calendars available for use, I am yet to find one that consistently provides the correct results

for now please change the calendar type in display settings to `Islamic (civil)`, it should fix your issue

**Comment by meypod** [comment]
App uses pre-calculated calendars, and so is not aware of moon sighting of the real world. and it does not use any website to find out
so, as a user, you can't rely on the app's calendar to know when Ramadan starts or ends exactly (for Eid Al-Fitr)
It's possible that some calendars types that I have included in app align with it perfectly some years, but you shouldn't rely on that

I'll show a notice some days before Ramadan starts, and another before it Ends, in future versions to let users know about this

**Comment by meypod** [comment]
Moved calendar settings to calculation page and Included a notice in latest version for this
