### ISSUE TITLE
Settings/Display/Numbering system

### ISSUE THREAD

**Issue by adlytaibi** [meypod/al-azan#42]
Please update the selection of numbering system to read something like:
Arabic Numerals refers to (0123456789)
Hindu Numerals refers to (٠١٢٣٤٥٦٧٨٩)
...
reference:
https://en.wikipedia.org/wiki/Arabic_numerals

**Comment by meypod** [comment]
If thats Arabic, then What's latin ?
From what I see, eastern arabic numerals are what you describe Hindu

[In js intl its called arabic-indic, but short code is 'arab'](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/numberingSystems#supported_numbering_system_types) 

So I'm not really convinced

**Comment by meypod** [comment]
Also check this part of the link you sent:
https://en.m.wikipedia.org/wiki/Arabic_numerals#Comparison_with_other_digits

So I think it's correct as is

**Comment by meypod** [comment]
Actually I think we both are confusing numerals with script.

both are Arabic numeral

but one in Arabic script (٠١٢٣٤٥٦٧٨٩)
the other in Latin script (0123456789)

**Comment by adlytaibi** [comment]
I'm only pointing out that what you're calling Latin is Western Arabic.
Here is a screenshot from another prayer app.
![IMG_20230417_185907](https://user-images.githubusercontent.com/30149504/232572612-0457a67a-e6db-4fd8-9785-d693aecdf1f1.jpg)

**Comment by meypod** [comment]
Well you never mentioned "western" vs "eastern" and said "Hindu" numerals which confused me

Anyway, I'll change "Latin" to "Western Arabic" and "Arabic" to "Eastern Arabic" in the next version
