### ISSUE TITLE
Azan stopping

### ISSUE THREAD

**Issue by HyperrJedi** [meypod/al-azan#43]
I have downloaded this app for a couple of days, but everytime the azan plays, within the first 15 seconds, it stops playing, not completing the azan.

**Comment by meypod** [comment]
Hi
can you tell me your android version, brand, app version, and if you have disabled battery optimizations for it ?

**Comment by HyperrJedi** [comment]
Android version: 13
Brand: Samsung
App Version: 1.12.0
Battery Optimization: I have battery optimizations disabled

**Comment by meypod** [comment]
latest version of the app is 1.13.4 right now, which includes many fixes that are not yet available on f-droid yet (it will be in next week probably)
If you are willing to, please uninstall f-droid version and install latest version from [GitHub releases](https://github.com/meypod/al-azan/releases/tag/v1.13.4) page to see if your problem is resolved
otherwise you have to wait till the app is updated on f-droid to see if issue persists

**Comment by HyperrJedi** [comment]
After using the apk, the issue still persists. Sometimes, it doesn't even play anymore.

**Comment by meypod** [comment]
that is strange
are you sure samsung's special power manager isn't putting app to sleep ? (when it doesn't play anymore)
I have seen on my relative's device (old samsung) that this happens by accident
I wish I could have more info

are you familiar with using a tool named adb? if you do, I'd like to get some info using that
it's fine if you are not, but it can help a lot

**Comment by HyperrJedi** [comment]
I have checked out the website and have now done everything that I can. I have 2 questions. When I open device care, then go to apps that never sleep, your app doesn't show up on the list. Why is that? Another one is why does this affect your app? I have used other Azan apps like Quranmajeed and this never occurred on that.

**Comment by meypod** [comment]
well I don't know why it doesn't show up there
this affects my app because I'm using the standard Android api
there may be some special way to do it on Samsung devices that I'm not aware of
I'll check the app you mentioned

**Comment by meypod** [comment]
I noticed the app you mentioned asks for auto start permission as well
if the stuff you did didn't work, try granting auto start permission to Al-Azan app and see if it works

thank you for trying this out

**Comment by meypod** [comment]
since I haven't heard from you in a week, I assume that your problem was solved
if your problem was not solved and you think there's something that needs to be done on my part please tell me
