### ISSUE TITLE
Add option to select different adhan for each prayer time

### ISSUE THREAD

**Issue by Ekinci2022** [meypod/al-azan#44]
Hello. I would like to choose our own select to azan all times. For example, you have selected only for fejr, but I want to set the azan mp3 that which i want for prayer times. Is this possible? can you add this?

**Comment by meypod** [comment]
Hi
While I have laid some foundation if such feature was to be ever implemented, I'd rather not do it, because I am not sure about how to display the settings to user
you see right now it has a simple UI, but what happens if each prayer can have custom adhan ? how would one know which adhan plays at which time, without making it complex ?

**Comment by Ekinci2022** [comment]
I would like to choose azan as a maqam. for example for maghrib segah, for isha hijaz... That's why I wanted it.

**Comment by Ekinci2022** [comment]
We can adjust the notification settings for Fajr. When you click on 3 dots, other times can be selected from the same setting area. it wouldn't be complicated

**Comment by meypod** [comment]
the problem is in showing which is selected for when, for fajr, there was enough space to add another check, but we can't do the same for other prayers

**Comment by Ekinci2022** [comment]
Can't it be done by adding dropdown? this should be very easy for you...

**Comment by meypod** [comment]
doing it is easy
I only want to keep it simple ( I already feel I have added so much features that it has become complex )
and dropdown doesn't seem to be a good idea (but It's probably the best available, but I don't like the idea overall)

**Comment by meypod** [comment]
I'll keep this issue open and think about it for a while

**Comment by meypod** [comment]
Keep in mind that not everyone is smart, I have close relatives that get overwhelmed easily just by the amount of options available in the app and ask for help

**Comment by Ekinci2022** [comment]
this request should be a very simple process for a good dev like you 😀 the application is more practical and understandable than most azan applications on google play. I don't think it will be anything confusing. I will only choose one of the names of prayer times that come out by pressing the 3 dots next to the azan mp3 that I have downloaded. I don't think this is complicated.

**Comment by meypod** [comment]
I understand
but I guess I was not clear enough 😅
I didn't mean my relatives _will_ ask if I add this, they _already_ have asked, and they have asked about adding a custom adhan specifically as well
so I am pretty sure, there are people that find this confusing already to a degree (not that it can be any simpler, really)
So I'm really not sure how to approach this

**Comment by Ekinci2022** [comment]
I understand. thanks for your answers. I will be waiting for this feature 😁with prayer....

**Comment by Ekinci2022** [comment]
hello, any progress?

**Comment by meypod** [comment]
Hi,
I'm sorry, I'm busy with another task at the moment, I'll look into it when I have time

**Comment by Ekinci2022** [comment]
thanks a lot. I will try

**Comment by meypod** [comment]
In the muezzin settings, there's a button on top right labeled "Advanced", pressing it will reveal the new menu. 
thank you

**Comment by Ekinci2022** [comment]
everything looks alright. I could choose the prayer I wanted and there was no problem. Thanks a lot :) I think you should add a donate button

**Comment by meypod** [comment]
Glad it's working fine
Thank you for testing
Sadly I can only accept in crypto, I have added the wallet addresses to the [Github readme](https://github.com/meypod/al-azan)
