### ISSUE TITLE
App feezes at the end of initial setup.

### ISSUE THREAD

**Issue by E1K4M41** [meypod/al-azan#45]
Assalaamualaykom. 

Everytime I try to setup the app, everything goes well until the end the setup. As soon as I validate it, the app freezes.

**Comment by E1K4M41** [comment]
According to F-Droid it is the 1.12.0

**Comment by E1K4M41** [comment]
According to F-Droid it is the 1.12.0

**Comment by meypod** [comment]
Can you try using the [latest version (1.13.4)](https://github.com/meypod/al-azan/releases/latest) from github ?

**Comment by E1K4M41** [comment]
It seems to be working now. 
Thank you very much.

**Comment by meypod** [comment]
I'm glad I could help :)
