### ISSUE TITLE
There is not sunset time in adjusment part in calculation part

### ISSUE THREAD

**Issue by RZHSSNZDH** [meypod/al-azan#49]
**Describe the bug**
 When I go calculation part and adjustment to edit adhan and other times, I can't see sunset time. There is sunrise, but not sunset.

<details>
  <summary>Screenshots</summary>
  
![Screenshot_20230414-055945_Al-Azan](https://user-images.githubusercontent.com/69734726/233089972-bcf314b3-4f81-4387-820e-c510c2859bb2.png)

</details>

**Device Info :**
 - Device: Gapaxy J7
 - OS: Lineage 17.1

**App Version:** 1.14.0
**F-Droid:** Yes

**Comment by meypod** [comment]
I'll try to add all remaining times in the upcoming version

**Comment by meypod** [comment]
it seems that midnight and tahajjud dont need adjustment, because they are calculated based on Fajr and Maghrib

I have added sunset as well
will be released with the next version

**Comment by meypod** [comment]
release in [v1.14.1](https://github.com/meypod/al-azan/releases/tag/v1.14.1)
