### ISSUE TITLE
Arabic numbers 123 instead of indie ١٢٣

### ISSUE THREAD

**Issue by imlinstress** [meypod/al-azan#5]
could you please give us a chance to decide which numbers to use, like for the islamic date?

**Comment by meypod** [comment]
can you give me more detail ?
do you mean to select islamic calendar locale or english/arabic numbers ?

**Comment by imlinstress** [comment]
That would be awesome!
By the way, great App.

>
![Screenshot_20220923-102339_Al-Azan](https://user-images.githubusercontent.com/81245312/191931749-f2984ec1-a8d8-4d01-91d3-2b0c9b6cc33d.png)

In this screenshot for exemple, it nice to have 
الجمعة، 26 صفر 1444.
Same thing for the widgets.

Speaking of which, جمعة مباركة

**Comment by meypod** [comment]
added this in [v1.1.1](https://github.com/meypod/al-azan/releases/tag/v1.1.1)
