### ISSUE TITLE
Dagestan

### ISSUE THREAD

**Issue by VRT-secure** [meypod/al-azan#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Assalamy alaykum my brother, please add the Makhachkala city to the app, in my city a lot of muslims alhamduliLlah. 

**Additional context**

**Comment by meypod** [comment]
wa alaykum assalam

my app doesn't save any city name anywhere
it uses geonames.org website to search the cities
so I can't really add it anywhere

you have to send your request to that website, which I don't know how either

**Comment by meypod** [comment]
It seems searching for `Makhach-Kala` makes it come up in search
