### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by Tvirin** [meypod/al-azan#51]
the buttons cannot be pressed, see the picture

 ![11111](https://user-images.githubusercontent.com/93820884/235090580-01030697-5567-4f02-afe0-217bf65d2344.jpg)

**Comment by meypod** [comment]
Hi
Thanks for reporting this, I wasn't aware
I'll fix this in coming days

**Comment by meypod** [comment]
released fix in [v1.14.3](https://github.com/meypod/al-azan/releases/tag/v1.14.3)
google play releases are delayed for the time being
f-droid will be updated automatically in a week or so

**Comment by Tvirin** [comment]
Thank you very much for your quick response.

But screen is not small, this is Huawei Nova 9 SE with normal font size.

**Comment by meypod** [comment]
I understand

But this is definitely happening on smaller screens
It's just changelogs, the issue is definitely solved :)

Please let me know if such issues exist in any other place after this release
