### ISSUE TITLE
Is there a daylight saving option that could bevenabled?

### ISSUE THREAD

**Issue by khaledmust** [meypod/al-azan#52]

**Comment by meypod** [comment]
Hi
No there isn't
Dst is handled by the OS
So if your android device has option for it, disabling it should also change the times in the app

You need to change any calculation settings in the app to reset the app's cache after disabling it in android settings to see the correct times

**Comment by khaledmust** [comment]
> Hi No there isn't Dst is handled by the OS So if your android device has option for it, disabling it should also change the times in the app
> 
> You need to change any calculation settings in the app to reset the app's cache after disabling it in android settings to see the correct times

Thank you.
