### ISSUE TITLE
azan time bugged

### ISSUE THREAD

**Issue by MohamedIraqi** [meypod/al-azan#53]
After the daylight savings time change in egypt my oppo a16 running colorOS v11.1 didn't change the time of azans, and I can't find anything related to the daylight saving change in the app settings

**Comment by meypod** [comment]
Daylight saving is a settings of the OS

However, you are right that app probably didn't update it's times accordingly
You can reset app's times by changing the calculation settings (anything works, simply select another method for a second then select back your own)

If the issue persisted, please let me know

**Comment by MohamedIraqi** [comment]
> Daylight saving is a settings of the OS
> 

I'm aware of that, but this particular os doesn't have any setting to fix this so I had to change it to manual, I tryed changing the calculation settings and it didn't work

**Comment by meypod** [comment]
I'm sorry, but there is little I can do about daylight time savings

to support this I have to rewrite important parts of the app, which is not easy and I'm very busy at the moment

maybe in future I reconsider doing this, but for now I cannot
I'm really sorry that this is causing inconvenience for you

as an unrelated note:
Manually changing your time will have effect on your phone's ability to use certain programs and even the internet
many systems require that your time be in sync with global time. when you change your time you may go behind or after the global time, which will break certain checks that needs to be done for certain programs.
the best way to fix this currently is if you have root access, you can go and edit your phone's timezone data, which will fix it the right way. this is for advanced users though and I don't recommend it if you are not familiar with android internals.
