### ISSUE TITLE
Prayer Times are in wrong Order on the Widget

### ISSUE THREAD

**Issue by tegutistgut** [meypod/al-azan#55]
As you can see, the Prayer times are at a completely wrong order. I marked them on how they should be (from 1 to 6). The order is wrong at any language. 

It starts from right to left, it would be very very good if we can change it to left to right

![Screenshot_20239342618.png](https://user-images.githubusercontent.com/56385412/236806437-ae21f378-a856-4a2a-9170-373b1a9bf7f4.png)

**Comment by meypod** [comment]
Thanks for reporting this, I didn't pay attention to this at all
this is actually not wrong in any language, it is right in RTL (Arabic, Persian, etc) languages and wrong in LTR (English, German, etc)

I'll work on this when I have time :)
