### ISSUE TITLE
Saving More Locations

### ISSUE THREAD

**Issue by matt873** [meypod/al-azan#57]
For instance, if someone has a 50km distance between work and home, then it is very useful to have more than one location saved for easy switching between them just like geometric weather has. And many people don't keep location service on, so this feature will be really helpful.

**Comment by meypod** [comment]
hmm
al-azan currently does not update the location automatically, It only uses GPS once, when you press use my location
while the feature you mention seems nice, it adds unnecessary complexity in my opinion
many phones come with a "dual app" feature or sth like that, for now, you can duplicate the app and use that if your phone provides such a functionality

This feature raises some questions, Like:
- How should the app handle multi location functionality ? how would the UI look like ? how would the UX be like ?
- Which location should be used for notifications and sounds ?
- The switch between locations should be manual, or should be automatic ?
- if automatic, time based switching should exist ? Like 7:00 till 16:00 use different location, then switch back ?

these are questions that requires some thoughts

those aside,
remember, there's an infinite number of things and features that would be nice/can be done, but each feature adds more complexity. older people may find it daunting to use the app as it gets more complex, and I feel it is already complex.

and at the end I cannot possibly add every feature, such features take a lot of time.

**Comment by matt873** [comment]
I used to clone the app on my Xiaomi phone but after switching to Pixel, I felt it was needed because Pixel doesn't provide dual apps support.
You can just add saving location like geometric weather. There is no need to schedule switching. This should be manual. Yeah, I acknowledge that it requires time and effort due to the UI UX thing.

**Comment by meypod** [comment]
@matt873  I have added a new menu in [1.17.0-rc5](https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc5) which you can access from home screen, by pressing the name/coordinates that is shown under the lunar calendar:

![image](https://github.com/meypod/al-azan/assets/106489260/cd360be1-217d-40bc-bb5c-10ca2ecc796f)


In this new menu you can add coordinates/cities you want and name them, and quickly switch between them easily
it would be nice if you could download the new preview version and give me feedback

**Comment by meypod** [comment]
I have applied a few style fixes, get [v1.17.0-rc6](https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc6)

**Comment by matt873** [comment]
Thank you for implementing this feature. I tested and it's working fine. Loving this simple and very useful app😍!

**Comment by meypod** [comment]
I'm glad you liked it

**Comment by matt873** [comment]
Can you add an option to display the current location in the widget?

**Comment by meypod** [comment]
Adding this is quite hard right now
because:
- widget is already cramped
- it is shared between home screen and notification
- each option means 2x the file variants.
![image](https://github.com/meypod/al-azan/assets/106489260/496f114a-7044-4e61-aacc-3924e3eabc5c)


but, if I don't modify the layout, and add it like for example, prepended to the secondary calendar in the widget, it may be possible much more easily
