### ISSUE TITLE
[Feature Request] Adjustable upcoming adzan alarm notification/reminder

### ISSUE THREAD

**Issue by bayazidbh** [meypod/al-azan#58]
**Is your feature request related to a problem? Please describe.**
The upcoming alarm notification is good, as it allows me to prepare to finish my current business, take wudhu, and start walking to the mushalla.

But one hour is too long, and I'm liable to just dismiss it and forget about it as I continue with my work or entertainment. 30 minutes works better for me. I could get that through the Reminders system, but that seems tailored towards per-adzan specific reminders, rather than application-wide notification.

**Describe the solution you'd like**
Either add a few common options ranging from 5 minutes to 1 hour, or add an input field for how long people would prefer their pre-adzan notifications would be.

**Comment by meypod** [comment]
I'll work on it when I have time

**Comment by meypod** [comment]
This has been added as a list of pre defined times that you can select from in the latest release candidates

it will be released as stable in the coming days/week

**Comment by bayazidbh** [comment]
Hm, I've tested rc8, but I haven't noticed the upcoming adzan alarm. Is it provided as a toast notification or something? I was hoping for a normal notification/alarm.

**Comment by meypod** [comment]
It is indeed a normal notification
But it is not intended as alarm
Its the same as before, just you can adjust the time of it showing up
