### ISSUE TITLE
[Feature Request] Notifications without activating the screen

### ISSUE THREAD

**Issue by AI-IMED** [meypod/al-azan#59]
Hello,
It would be nice to have a preference to prevent the screen from waking up when notifications of azan times go off, I don't need to wake the screen as long as I know what time I am and when the azan ends.

**Comment by meypod** [comment]
I'll look into it when I have time

**Comment by meypod** [comment]
implemented in [1.17.0-rc1](https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc1), please test

**Comment by AI-IMED** [comment]
Thank you very much
