### ISSUE TITLE
Prayer times adjusting minutes on the App

### ISSUE THREAD

**Issue by imlinstress** [meypod/al-azan#6]
Would it be great if one could tweak the exact local prayer times by adjusting the minutes after chosing the calculation method.

**Comment by meypod** [comment]
sure, this is something I had in mind by seeing other apps, I'll add it soon

**Comment by meypod** [comment]
sorry this took long, was busy with other stuff

should be released with https://github.com/meypod/al-azan/releases/tag/v1.4.0
feel free to create an issue if you have any problem
