### ISSUE TITLE
Bangla translation of "phone permission dialog" need a small fix

### ISSUE THREAD

**Issue by Tanzin01** [meypod/al-azan#61]
There is a incomplete sentence due to a word missing.

**Comment by meypod** [comment]
@SaminYaser-work can you confirm this ?

**Comment by SaminYaser-work** [comment]
@Tanzin01 were you talking about this? 
![image](https://github.com/meypod/al-azan/assets/40205522/dd979c5f-e021-44f5-ba63-069d9927e80d)

**Comment by meypod** [comment]
thank you for the fix, I'll release the updated translations in the next release :)

**Comment by Tanzin01** [comment]
@SaminYaser-work yeah that one.
