### ISSUE TITLE
Add Duha prayer

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#62]
Hi, can you please add reminder for duha prayer and also add it to "Widget Settings" and   "Notifications & Sound"?

**Comment by meypod** [comment]
Hi

App already has a general purpose "Reminder" in settings, you can use it to add reminders for Duha and other things

**Comment by TorCzaf** [comment]
Ah yes I forgot there is reminder,  How about adding duha to main screen like the other 5 prayers or adding it to widget?
Or you think reminder is enough?
----------
By the way your app is indeed excellent.
I understand you want to keep it simple and I don't know if you will update your app someday to be more than just Azan and qibla app like adding quran to it, But I want to tell you the more features it gets, the more excellent, better and more popular it will become, that is my opinion. 
I support  your app mainly because it is [("Privacy-first") and doesn't even have a single tracker] and also "open source".
 I think it is rare to find islamic apps that are open source and in same time focus on Privacy.

Anyways, I only give suggestions, and Jazak Allah Kheer.

**Comment by meypod** [comment]
I'm sorry but main screen is already cramped and it's scrolling for older people who use extra large fonts (I have seen this first hand)

Quran feature alone needs careful design and execution, which is out of scope of this app, and it will increase the app size significantly, but there's already good open source Quran app: https://github.com/AlfaazPlus/QuranApp

thanks for your kind words

may Allah reward you as well
