### ISSUE TITLE
Add enable vibration  and dua after azan buttons

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#65]
Hi can you please add a button to enable vibration when the app does Azan?
I mean when azan happens, vibration happens. 

Also it would be good to add button to enable dua after azan if possible.

**Comment by meypod** [comment]
Hi
I plan to add settings for vibration in future
for dua you can use a custom adhan audio with dua after it :)

**Comment by meypod** [comment]
App already vibrates once when playing adhan though
make sure to check your phone and app's notification settings

**Comment by jd1378** [comment]
That's a native app in kotlin
Al-Azan is react native (javascript)
we cannot use any of their components :)

**Comment by meypod** [comment]
That's a native app in kotlin
Al-Azan is react native (javascript)
we cannot use any of their components :)

**Comment by meypod** [comment]
sorry, but I don't plan to add more adhan voices

I understand that you like the app and want more features on it, no need to apologize :)

**Comment by meypod** [comment]
added this in [1.17.0-rc1](https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc1), will soon release as stable 1.17.0, please test

**Comment by meypod** [comment]
Hi, Thanks for testing it
I think I realized the problem

the problem is that when you change, it will only take effect when they are rescheduled, it does not take effect immediately 

will work on a fix soon
