### ISSUE TITLE
The possibility of adjusting the midnight time

### ISSUE THREAD

**Issue by AI-IMED** [meypod/al-azan#68]
It is necessary to make the midnight time adjustable, or to provide a separate option to that, due to the difference of some jurisprudential opinions.

**Comment by AI-IMED** [comment]
Oh, you're right, I opened an issue there.

**Comment by AI-IMED** [comment]
@meypod What do you think of a separate option as found in the Five Prayers app, in case the midnight time adjustment issue in adhan-js is not addressed?

![Screenshot_20230709-203736_Five Prayers](https://github.com/meypod/al-azan/assets/38974362/86717b28-15eb-413e-8de4-af88f8077016)

**Comment by meypod** [comment]
if it's not addressed then I will fork the project and update it to suit our needs

**Comment by meypod** [comment]
@AI-IMED added this feature as well, please test https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc1

**Comment by AI-IMED** [comment]
Thank's, I was hoping that the adjustment was manual because there is still a difference of one minute and sometimes two minutes.

**Comment by meypod** [comment]
Well midnight is calculated based on sunset and fajr or sunrise
So if you have one minute error in each, it ends up like 2 minutes error in midnight

**Comment by meypod** [comment]
still I have added the independent final adjustment for midnight as well,
will release in 1.17.0-rc3 (maybe a few days later)

**Comment by AI-IMED** [comment]
Thank you very much, I'm excited about the feature of adding custom angles as well.
