### ISSUE TITLE
Add a button to clone reminder

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#70]
Hi can you please add a button to clone reminders  so I don't have to create a new reminder again and adjust its settings again?
This is important especially in case if someone reinstalls the app.
Thank you.

**Comment by meypod** [comment]
Hi
in case of reinstalling the app one can export the settings before uninstalling and import the settings after installing again, which will bring back all the settings except the custom sounds.

**Comment by jd1378** [comment]
What do you mean by "somebody has no space in his phone" ? 
I am a bit confused about what you exactly mean
can you explain more where do you expect to see this button and what it does ?

**Comment by meypod** [comment]
data export is super small (few kilobytes), so a user can almost always export their data

other than being confusing for anyone seeing it for the first time, I think this is okay. 
I'll add this when I have time :)

**Comment by meypod** [comment]
Added  this feature, please test [1.17.0-rc1](https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc1)
