### ISSUE TITLE
Prayer times calendar

### ISSUE THREAD

**Issue by AI-IMED** [meypod/al-azan#73]
Hi,
It will be convenient to display prayer times in bulk (each month in a screen) for a broader and more comprehensive look at the prayer times for each month, in addition to that this method will make it easier to compare the times of each month after adjustment with the required times, it is an easy alternative to the very tiring day-by-day commuting method.

**Comment by meypod** [comment]
Hi
While it may be nice to have, I think this is not useful at all, as we only need to know the adhan times on a day to day basis
but still I wanted to implement it at some point
I'll try to implement on my free time

**Comment by meypod** [comment]
sorry I did not read properly
that's fair usage actually
still, will try to implement it anyway

**Comment by AI-IMED** [comment]
You have all the time whenever you want, the benefit of this is to make it easier to review prayer times for several months and quickly after making adjustments

**Comment by meypod** [comment]
Please try https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc8
you can open monthly view by pressing the calendar text on top left corner

**Comment by AI-IMED** [comment]
Thank you very much!
I have a few suggestions to make the experience easier and more useful:

- Show Hijri date
- Move between months by swiping with fingers
- Enable the 12-hour time format feature with calendar
- Enable the feature of hiding prayer times that I do not want to see with the calendar, as in my case, I do not need to display Asr and Isha times.

![٢٠٢٣٠٧٢٨-٠٩١٣٥٨](https://github.com/meypod/al-azan/assets/38974362/0dde78f0-1ee5-4a5d-84ed-9df335cce654)

**Comment by meypod** [comment]
I have added hijri date toggle and allowed using 24 hour format from settings
and highlighted the current day if it's in view
will make a rc soon

**Comment by meypod** [comment]
as for other features:
swiping on main screen makes sense as it's fast enough to respond now, but in monthly view it really isn't great as there's no indicator of loading, you won't even know the app is stuck loading the next state if you don't press the buttons (I tried hard to fix some major performance issues the app had for long, but still couldn't make the screen render instant here)
Hiding current prayers/Showing extra prayers requires extra settings page/dialog, which I'm not willing to add to the app right now as it takes some time

thanks for the suggestions :)
