### ISSUE TITLE
Vibration does not work

### ISSUE THREAD

**Issue by AI-IMED** [meypod/al-azan#75]
The phone does not vibrate when the call to prayer/reminder starts at all, whatever the vibration mode is continuous or once.

**Comment by meypod** [comment]
Did you try latest rc ?

**Comment by AI-IMED** [comment]
Yes I have rc7, Vibrations aren't working.

**Comment by meypod** [comment]
please go to the about page
press on "version" multiple times till you see a toast message
then restart app
then go to dev menu in settings
then check if any of the vibrates work for you

**Comment by meypod** [comment]
np, I'm glad it's working
