### ISSUE TITLE
Make the app more customizable (excluding customizing azan)

### ISSUE THREAD

**Issue by Growebis** [meypod/al-azan#78]
**Is your feature request related to a problem? Please describe.**

Currently, you can't really customize the app outside of changing the theme from dark mode to light mode. (btw I'm not talking about what to display when you open the app, as that's already customizable). 

**Describe the solution you'd like**

Make it possible to change the theme to any color possible. While at it make it possible to change text color to any color. Also allow the accent color to be customizable.

**Additional context**

I think this is low priority since the main objective of the app is for azan and not looks but it makes the app fit with the theme of the OS considering Material You exists.

**Comment by meypod** [comment]
hi
thanks for taking your time to suggest,
but this takes a lot of time, specially in react native, and is not planned
