### ISSUE TITLE
Errors appearing in the application when the system language is an RTL language

### ISSUE THREAD

**Issue by AI-IMED** [meypod/al-azan#79]
- Correct layout and alignment is not applied when the application language is changed to one of the LTR languages ​​such as English:

![٢٠٢٣٠٧٢٨-٢٢٠٤٣٩](https://github.com/meypod/al-azan/assets/38974362/dffacc48-ca24-49f8-a611-1e53993bd9a7)

- The Western Arabic numbering system is not enforced, although it is specified within the application settings:

![٢٠٢٣٠٧٢٨-٢٢٠٨٢٩](https://github.com/meypod/al-azan/assets/38974362/52484d18-180c-4ca4-b6e4-c4490fe5e17e)

**Comment by meypod** [comment]
First one shouldn't be happening, can you give more info about how it happens ? because on my phone it is applied correctly

second one I can't do anything about, because the timer's text does not come from inside the app, it is provided by the OS, and I did not find a way to apply a locale to it while I was adding it

**Comment by meypod** [comment]
Ok it seems the bug happens if OS itself is in RTL language

**Comment by meypod** [comment]
related issue on react-native repo: https://github.com/facebook/react-native/issues/33423
I've been using the workaround suggested there from the beginning
when OS is LTR, RTL and LTR both work as expected,
but when os is RTL, it fails in LTR languages

**Comment by AI-IMED** [comment]
By the way, I use Arabic as the default language of the operating system in my phone, I can assure you that all the applications in my phone that allow changing the language from within the application can display the correct layout and alignment when switching to English for example.

**Comment by meypod** [comment]
This is a react native bug, I'm sure it is possible to show the proper layout in normal native apps

**Comment by meypod** [comment]
Ok I found the issue in my code
Will release the fix with next release

**Comment by AI-IMED** [comment]
I have a question about the backups that I create with the latest versions, is the failure of older versions to import these backups normal?

**Comment by meypod** [comment]
hmmm
I can't say that it's not normal
export from old should be able to be imported on new versions, but in your case:
does it fail completely or you mean like some stuff are missing ?
does the app crash ?
what happens exactly ?

**Comment by AI-IMED** [comment]
Yes, the app crashes

**Comment by meypod** [comment]
that is not normal, the app should not crash, instead it should have shown a Toast saying it failed
are familiar with using adb tool?

**Comment by AI-IMED** [comment]
Unfortunately, I don't know how to use adb tool :)

**Comment by meypod** [comment]
It's okay
thanks for letting me know that this issue exist
but unfortunately I have no idea why it might be happening

**Comment by meypod** [comment]
btw [v1.17.0-rc12](https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc12) with layout fix is released now
