### ISSUE TITLE
App stops working after some time

### ISSUE THREAD

**Issue by meypod** [meypod/al-azan#8]
I have received a few reports where app does not work anymore after some time

While I had no problem so far, I believe this issue exists.
I really have little to no idea about why it happens, but it generally should be related to android battery saving mode.
I'm currently investigating why this happens, but I would appreciate any thoughts I can get on this.

**Comment by muava12** [comment]
just installed the app..

**Comment by meypod** [comment]
So far all cases were the OS killing the app in the background
If you find this app not working as expected, please check https://dontkillmyapp.com/ before commenting here

**Comment by meypod** [comment]
Part of the problem seems to be from my fork of notifee core
I've released an update for it with [v1.4.5](https://github.com/meypod/al-azan/releases/tag/v1.4.5)
hopefully the issue will be fixed
