### ISSUE TITLE
Times are not true

### ISSUE THREAD

**Issue by abdullahnil** [meypod/al-azan#81]
Hi, firstly thanks for app. I live in İzmir, Türkiye. I used source for Diyanet İşleri Başkanlığı.

When I comparing the original Diyanet calendar, there have some little differences. Why its happens? What I did wrong for settings? ![IMG_20230730_003036_566.jpg](https://github.com/meypod/al-azan/assets/77257895/e7399c89-1ba1-46ee-a9fd-3638d98dcd39)

**Comment by meypod** [comment]
Hi

sadly, the diyanet method provided by the app is an approximation, because it is not clear exactly how diyanet method calculates adhan times
it is discussed and tracked here, in the library I use for calculating prayer times: https://github.com/batoulapps/adhan-js/issues/154

**Comment by jd1378** [comment]
For your case though, the one minute difference is probably rounding error

**Comment by meypod** [comment]
For your case though, the one minute difference is probably rounding error

**Comment by meypod** [comment]
yeah, rounding difference

**Comment by meypod** [comment]
no, approximation is different
by rounding I mean when times are calculated, they are rounded to the nearest minute
adhan-js (the library I use to calculate time) has an option for selecting the rounding method If I remember right
I try to add it in future as an advanced option in calculation settings
I'll keep the issue open till then

**Comment by meypod** [comment]
added rounding method as an advanced option in calculation settings
