### ISSUE TITLE
[Bug] Error while trying to get coordinates.

### ISSUE THREAD

**Issue by Growebis** [meypod/al-azan#82]
**Describe the bug**
 
For some reason, everytime i try to use GPS for calculating the azan, i always get "Error while trying to get coordinates" trying to use my GPS while on other applications that use locations works perfectly fine. Nothing was obsctructing the GPS btw.
**To Reproduce**

1. Open the app.
2. Go to location settings
3. press Find My Location
4. The error pops up after some time has passed while its trying to determine my location.
**Expected behavior**

For it to automatically know my location and to calculate the azan.

![Screenshot_20230730-171418](https://github.com/meypod/al-azan/assets/113867283/a16f88aa-8ca1-47a7-b5b4-84254a0a968e)

**Device Info :**
 - Device: Sony Xperia L1
 - OS: Android 7

**App Version:**
**F-Droid:**  No
Using pre-release version v1.17.0-rc14.
I also tried using the latest F-Droid version and same thing happens.

**Additional context**

Perhaps the app has a set amout of time for finding the location and if that time passes it just gives up? IDK that is just my hypothesis.
This also happens in the welcome screen when you just downloaded the app.
This always happened. I don't recall a period where it worked.

**Comment by meypod** [comment]
Hi
It does have a timeout, but it should work
can you double check just in case that your location service is on ? 
does the icon appear when app is trying to fetch coordinates ? 
thanks

**Comment by Growebis** [comment]
Hi,

>  can you double check just in case that your location service is on ?


Yes it was on.

>  does the icon appear when app is trying to fetch coordinates ?

Yes. Just that the second it ended the icon disappeared. That's why its not there in the screenshot.

**Comment by meypod** [comment]
hmm, I'll try to increase the timeout for the next version by 10-15 seconds to see how it goes
it might help

**Comment by Growebis** [comment]
Just wondering, why would there be a timer for getting location data from GPS? shouldn't there be no timer so that phones that might have bad gps still get the coordinates even after 15 seconds? Just asking.

**Comment by meypod** [comment]
Im not sure why, the library i use specifies one
But regardless of the actual underlying reason, a user wouldn't wait more than 30s or so, and I can't stop the fetch after it starts until it's timed out
So if a user leaves the screen meanwhile or wants to use another method, I can't do anything about it, which can have unexpected results
So it's better to have a short time out duration

I'll double check later though to see if I really can't stop, if I find out I can I maybe change the way things work, but its unlikely

**Comment by meypod** [comment]
I checked, didn't provide a way to stop
increased the limit to 25 seconds in [v1.17.0-rc15](https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc15)
