### ISSUE TITLE
Increase reminder time option to help with Al-Awabeen prayer

### ISSUE THREAD

**Issue by MrNewbie72** [meypod/al-azan#83]
**Is your feature request related to a problem? Please describe.**
I want to put a reminder for Al-Duha prayer at a certain time that the prophet peace be upon him called it [Al-Awabeen prayer](https://mawdoo3.com/ما_معنى_صلاة_الأوابين).

**Describe the solution you'd like**
One easy way to tackle this problem is to add more timing options in the reminder section.
For example we can add a reminder before dhuhr prayer. but we are limited with the options 5, 10, 15, 30, 60 and 90 min adding the options 120, 150, 180 and 200. would be enough to put a reminder for that prayer in a flexible manner.

**Optimal solution** is to change the "Selection method" to make the user enter "Positive digit" which represents the minute and then it would be extremely fixable to achieve that and another benefit of this solution, is to actually use this app to put your routine reminders for other activities for example workout, while trying to tie those routines to prayer times instead of fixed times which if it was near a prayer it usually collides with a prayer time and force you adjust the reminder every time that happens (on normal reminder apps), and this fairly happens a lot.

Thank you for such wonderful application, may Allah jalla jalaluh bless you with his knowledge and wisdom.

وجزاكم الله خيرًا

**Comment by meypod** [comment]
Hi
Implemented this feature, will be released with next version

**Comment by meypod** [comment]
released in [1.17.0-rc15](https://github.com/meypod/al-azan/releases/tag/v1.17.0-rc15) (will be available on stable soon)
