### ISSUE TITLE
Adding an option to hide the seconds in the countdown

### ISSUE THREAD

**Issue by programer00112** [meypod/al-azan#84]
AsSalaamu 'Alaikum wa Rahmatu Allaahi wa barakaatuhu,
Jazaaka Allaahu khayran for making this amazing app, wa Baaraka Allaahu lak
I wanted to open a feature request abut hijri date adjustment too but then saw that you're already working on it and made a pre-release that has it. This is really amazing and shows how fast your app is progressing, wa Baaraka Allaahu lak.
I would like to ask you please to add a function to hide the seconds in the countdown in the widget. It is very distracting to see the widget refreshing every second.

**Comment by meypod** [comment]
Wa alaykum assalam
I'm afraid android's chronometer component which is used in the widget does not support hiding seconds
and as far as I know, android does not support adding custom components to widgets, to ensure widgets are lightweight and battery usage is minimal
