### ISSUE TITLE
[Suggestion] Quick access to the backup

### ISSUE THREAD

**Issue by AI-IMED** [meypod/al-azan#87]
I think it would be great to have a button to access the one-click backup in the welcome screen instead of the current method that requires at least five clicks

![٢٠٢٣٠٨٠٨-١٠٣٣٠٥](https://github.com/meypod/al-azan/assets/38974362/51a39afb-88e6-44f1-a120-44555b246969)

**Comment by meypod** [comment]
I agree,
I was about to implement it 
also need a reminder to disable battery optimization for the app, because I keep forgetting myself

**Comment by AI-IMED** [comment]
Great job! Thank you very much.. At first it occurred to me that the word 'ok' in the reminder message meant auto-disabling in the background for the battery optimization feature :)
 I think changing "OKAY" to SKIP would be more clear.

**Comment by meypod** [comment]
well why would we remind the user if we could do it ourselves in the background 😄
I'm not sure about the word "skip" in this case, because the user is not dismissing anything

**Comment by meypod** [comment]
I'll use "dismiss" instead
