### ISSUE TITLE
Azan seems to randomly end for no reason at all.

### ISSUE THREAD

**Issue by Growebis** [meypod/al-azan#88]
**Describe the bug**
 
Sometimes, the azan ends randomly, this isn't consistent at all. Sometimes it ends at the beginning of the azan and sometimes in the middle of it. Sometimes the azan plays completely and nothing wrong happens.
**To Reproduce**

1. Wait for it to be prayer time
2. either it randomly ends in the beginning or middle. Or it plays fine,
**Expected behavior**

For the azan to play completely. 

**Device Info :**
 - Device: Sony Xperia L1
 - OS: Android 7

**App Version:**
**F-Droid:** Yes
1.16
I remember trying the latest pre release version (i think it was 1.17 rc13) and it also had the same issue

**Additional context**

Battery optimization is disabled

**Comment by meypod** [comment]
this sounds like a battery saving issue
have you tried disabling battery saving for this app ?
on some devices there's extra settings for this, watch out for that as well
please check https://dontkillmyapp.com/sony to see if your device is properly configured

**Comment by Growebis** [comment]
> have you tried disabling battery saving for this app ?


Yes

> on some devices there's extra settings for this, watch out for that as well
please check https://dontkillmyapp.com/sony to see if your device is properly configured

I will try to see if the azan plays with stamina mode on/off and see if that makes a difference.

**Comment by Growebis** [comment]
The azan still ends randomly even with stamina off.

**Comment by meypod** [comment]
there's two more solutions on that page, please check if those are available on your phone and try them as well

**Comment by Growebis** [comment]
> there's two more solutions on that page, please check if those are available on your phone and try them as well (Adaptive battery & Power-saving feature)

I dont have any of these .

**Comment by Growebis** [comment]
The last prayer application i used, which was Pillars, never had this issue ever. But maybe its because the azan is an alarm and not a notification? Because Pillars uses notification.

**Comment by meypod** [comment]
with notification we don't have control over what is played after the initial settings. so if pillars can change the audio from inside the app, they use the same technique as us.
but it shouldn't be the reason from what I understand
what adhan do you use ? custom sound or default adhan ?
for reference, can you install a third party alarm clock and set your custom adhan (if you use one) as the alarm sound and see if it plays till completion ? if possible, try both google's alarm clock and a less used one (to see if there's a whitelist)

this can help a lot 
thank you

**Comment by Growebis** [comment]
> what adhan do you use ? custom sound or default adhan ?

I use a custom azan.

> for reference, can you install a third party alarm clock and set your custom adhan (if you use one) as the alarm sound and see if it plays till completion ? if possible, try both google's alarm clock and a less used one (to see if there's a whitelist built into the phone's os)

I will try this and see if similar behavior happens.

**Comment by meypod** [comment]
also try to see if default adhan has the same problem or not

**Comment by Growebis** [comment]
Sorry for replying late.

I didnt have time to test it since i was extremely busy but maybe in the next couple days i will test.

**Comment by Growebis** [comment]
The issue seems to have resolved itself, as it has been a couple days and the athan never ended randomly.

**Comment by Growebis** [comment]
The issue is back but i think i know the cause.

When the adhan was playing fine for a couple days, i had no alarm setup (using the default clock app) so the adhan always played fully. But now when i setup an alarm in the clock app the inconsistent behaviour is back. I guess thats a cause that im not sure how it would be solved.

**Comment by meypod** [comment]
hmm
you mean you have an alarm, that fires like 1 minute after adhan ? and alarm starting causes adhan to stop ?

**Comment by Growebis** [comment]
> hmm you mean you have an alarm, that fires like 1 minute after adhan ? and alarm starting causes adhan to stop ?

no, what i meant is basically if i had an alarm setup, doesnt matter if its close to the adhan (in terms of time) or if its far apart from the adhan. it would still randomly end. like the sheer presence of having an alarm can make the app randomly end or not.

**Comment by meypod** [comment]
Try enabling this in settings and see how it goes

![Screenshot_2023-08-31-19-25-36-910_com github meypod al_azan-edit](https://github.com/meypod/al-azan/assets/106489260/df7f477d-a4c4-41b0-a230-59830a126ed5)

**Comment by Growebis** [comment]
Sure i will try this and report the result in a day or two

**Comment by Growebis** [comment]
nothing changed it still ends randomly.

**Comment by meypod** [comment]
I'm sorry but this sounds like to be a device specific issue, so I don't think there's much i can do
I have asked you to try anything that came into my mind
I wish I could help you more

**Comment by meypod** [comment]
@Growebis can you test this please?
> for reference, can you install a third party alarm clock and set your custom adhan (if you use one) as the alarm sound and see if it plays till completion ? if possible, try both google's alarm clock and a less used one (to see if there's a whitelist built into the phone's os)

also tell me if your custom adhan plays till completion when you play it in the settings using the play button

**Comment by meypod** [comment]
I'm sorry but without more info I can't work on this and keep this issue open
