### ISSUE TITLE
Current location in Widget

### ISSUE THREAD

**Issue by matt873** [meypod/al-azan#90]
Since some will only rely on widget only for day to day prayer times, this feature will make us not to forget to switch location in app after moving to different location like moving from college's hostel to home at weekend. Thanks!

**Comment by meypod** [comment]
Hi
While it has been asked before, there's not much space left for location in the widget

However I plan to create a smaller widget, for the next minor update, which I will probably add it there

**Comment by matt873** [comment]
Sounds perfect but can add one variation of widget with location info in place of islamic calender? Saying this because I don't know if smaller widget will take away some other info from the current widget.

**Comment by meypod** [comment]
sounds like a good idea
I'll try to add this variant as well

**Comment by meypod** [comment]
released option to replace one of calendars with current location in [v1.17.2](https://github.com/meypod/al-azan/releases/tag/v1.17.2)
you can find it in widget settings
