### ISSUE TITLE
صامت وقت الصلاة

### ISSUE THREAD

**Issue by islam2hamy** [meypod/al-azan#91]
السلام عليكم

جزاكم الله خيرا وبارك فيكم على هذا التطبيق

لدى طلب , حيث اريد انت تكون هناك ميزة لتحويل الهاتف المحمول الى وضع الصامت اثناء فترة الصلاة
بحيث يكون هناك خيار على مستوى كل صلاة يتم تحديد فيه عدد الدقائق من بعد الاذان ثم يتم تفعيل وضع الصامت , وكذلك تحدد عدد دقائق الوضع الصامت , ثم الغاء وضع الصامت تلقائى بعد انتهاء هذه المدة

وجزاكم الله خيرا

**Comment by islam2hamy** [comment]
#80 , 3,4,5

**Comment by meypod** [comment]
و علیکم السلام و رحمة الله
وجزاك الله خيرا أيضا
وهذا ما خططت له في الموضوع الذي ذكرته (#80 )

**Comment by islam2hamy** [comment]
بارك الله فيك
