### ISSUE TITLE
Allow reminder to be sent on certain weekdays (like adhan)

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#97]
Can you add a setting to make special reminders for Jumu’ah prayer 

-Because some people may forget to Enable reminders for friday (Jumu’ah prayer) 

-Also Jumu’ah prayer needs special readiness that means some people may put several reminders for Friday..for example In some regions Jumu’ah Khutbah+Prayer=15 or 20 min..this is short time and the mosque where there is Khutbah may be far away and I may need to wake up early or get out of the house early 

-Also when Friday comes some people forget/don't realize that it is Friday (unfortunately that is a fact), due to sleeping or Khutbah sound is very low to be heard in some regions or maybe some people put same audio for all Daily reminders or other things
So I think "Dismiss" background color of Dhuhr Adhan Alarm screen should be Red in Friday instead of blue...so when the user sees red color whether he is sleeping or doing something else he should remember Jumu’ah prayer and I think this is important feature. 

As for Jumu’ah prayer setting, The setting should allow user to create reminders for Jumu’ah prayer (Before or after dhuhr adhan) 

And in Friday I think Jumu’ah prayer reminders should override any other normal reminders that are adjusted to be played at the time of Jumu’ah reminders and that should lead to make Jumu’ah Setting to have enable-disable button.
If enabled, then user should be able to create reminders for Jumu’ah prayer.
And of course "Dismiss" background color of Jumu’ah reminders Alarm screen should be Red and also please type somewhere in the alarm screen "Jumu’ah Reminder".

**Comment by meypod** [comment]
> I mean they forget to add a reminder or enable a reminder before Friday because the reminders in your app can be active every day and anytime and that's why people may need special reminders for Friday because Jumu’ah prayer may require special readiness.

then it makes sense to add a feature to reminder to allow it to be activated on certain days like Friday
that way it can be used for other purposes as well
this should be up to user to select a special sound or text for the reminder to be reminded, not the app

**Comment by meypod** [comment]
> Does that mean you will add a feature to reminder to allow it to be activated on certain days?

yes

**Comment by meypod** [comment]
implemented, will release with next version
