### ISSUE TITLE
Import static prayer timetables (CSV Files)

### ISSUE THREAD

**Issue by TorCzaf** [meypod/al-azan#98]
Hi Can you add an option to import static timetable for prayer times? I think this could be useful for countries which their angles or parameters are unknown...for example Oman and morocco provide prayer timetables.
![Screenshot_20230913-225009_Prayer Times](https://github.com/meypod/al-azan/assets/137301636/c1ca7ba1-b999-4299-a117-f8128af845d2)

**Comment by meypod** [comment]
hi

are you sure those provide "csv" format ? can you link to them ?

**Comment by meypod** [comment]
Yes, I wanted to know if there is any official csv format for those you mention

Overall this feature has many UX challenges that I don't think it's worth the time to implement

It's better to put the effort on finding the official angles and parameters.

I don't think I will be implementing this feature

**Comment by meypod** [comment]
> Unfortunately there are no official CSV Files for Oman and morocco
There are other websites that provide unofficial CSV Files like
https://www.al-habib.info/prayer-time/
This website includes CSV files for too many countries and even if a CSV file is not as accurate as the official Prayer Timetables, the user can adjust it using spreadsheet apps.

I still believe trying to find the official angles is a better idea. if the timetables are not accurate either, users can try putting in custom angles and see how accurate the calculated times are, and then adjust the minutes from the app settings. 

> Or if somebody doesn't understand the meaning of your app settings (Round up, High latitude, Polar resolution..ETC), then in this case the feature should be valuable.

If this person knows how to download a csv file and import it in a program, I believe he won't have a hard time using other features of the app

> For example I may modify app settings on somebody's phone and make favorite locations use appropriate CSV 

you are using an example that does not exist in the app as a feature yet

and actually right now one can export and import the settings of the app, so the advanced stuff also gets exported. and the simple person would only need to change locations, if needed.

> Sorry I didn't understand what "User Experience challenges" mean

there are some cases that needs extra attention, to name a few:
- a csv file is a limited set of times, even if it's a time table for a year, it will run out eventually. how should the app inform the user and get the new times ? what should happen when the times finish and app does not have new times ?
- time tables probably do not contain the extra times provided by al-azan, what should happen to those ? tahajjud for example
- what happens to the adjustment settings ? should we lock app features or should we provide more flexibility ?

I'm not asking you to answer the questions above, but I mean more questions such as these will probably arise during development that affects UX, and will increase or decrease the amount of time needed to develop the features

in the case of calculation settings per location, the problem becomes much more complicated. it means the UI needs to be changed completely and become location oriented. this calls for a different design ground up. development time aside, I feel like the app becomes much harder to use as well.

As the first user of the app myself, I don't want to deal with multi location settings at all
